FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir poetry
ENV POETRY_VIRTUALENVS_CREATE=false

COPY pyproject.toml poetry.lock* ./

RUN poetry install --without dev --no-root

COPY streamlit_app/ streamlit_app/

CMD ["sh", "-c", "cd /app/streamlit_app && poetry run streamlit run app.py --server.port=8501 --server.address=0.0.0.0"]
